/**
 * Central SEO config. Consumed by:
 *   - client/src/components/RouteSeo.tsx (renders per-route document metadata;
 *     React 19 hoists it into <head>)
 *   - scripts/prerender.mjs (route list + sitemap generation)
 *
 * Keep titles <= ~60 chars and descriptions ~150-160 chars, each unique.
 */

export const SITE = {
  name: "Digital Therapy",
  url: "https://www.digitaltherapy.io",
  defaultOgImage: "/og-image.png", // 1200x630, generated by the prerender step
  twitterCard: "summary_large_image",
} as const;

export type RouteMeta = {
  title: string;
  description: string;
  /** Override the site-wide OG image for this route. */
  ogImage?: string;
  /** og:type (default "website"). */
  type?: "website" | "article" | "profile";
  /** Exclude from sitemap.xml + emit robots noindex. */
  noindex?: boolean;
  /** sitemap priority 0.0 - 1.0 (default 0.7). */
  priority?: number;
};

export const ROUTE_META: Record<string, RouteMeta> = {
  "/": {
    title: "Digital Therapy | Private Operating Layer for Family Offices",
    description:
      "Digital Therapy builds the private operating layer for modern family offices -- unifying data, workflows, reporting, automation, and security under one trained team.",
    priority: 1.0,
  },
  "/capabilities": {
    title: "Capabilities | Digital Therapy",
    description:
      "Software, process design, and automation that multiply your family office's capacity -- data, reporting, AP/AR, ERP, and AI built around your operations.",
    priority: 0.9,
  },
  "/process": {
    title: "Our Process | Digital Therapy",
    description:
      "How Digital Therapy works: a focused on-site Discovery phase with embedded Fusion Teams, then build and transformation tailored to your family office.",
    priority: 0.8,
  },
  "/dt-brain": {
    title: "DT Brain -- On-Prem Automation Hub | Digital Therapy",
    description:
      "DT Brain is Digital Therapy's on-prem AI and automation hub: your data, your hardware, your rules -- private intelligence built for the family office.",
    priority: 0.8,
  },
  "/thesis": {
    title: "Our Thesis | Digital Therapy",
    description:
      "Why family-office transformation needs one trained team, not competing practice groups. The Digital Therapy thesis on Fusion Teams and structural change.",
    priority: 0.7,
  },
  "/partners": {
    title: "Partners | Digital Therapy",
    description:
      "A confidential white-label partner model for private banks and advisory firms bringing family-office transformation to their clients.",
    priority: 0.7,
  },
  "/vendors": {
    title: "Vendor Applications | Digital Therapy",
    description:
      "Specialist vendors: apply to join Digital Therapy's bench across data, cloud, ERP, automation, finance, and AI disciplines.",
    priority: 0.6,
  },
  "/team": {
    title: "Team | Digital Therapy",
    description:
      "Meet the Digital Therapy team -- leadership, specialist benches, and the alliances behind our family-office Fusion Teams.",
    priority: 0.7,
  },
  "/terms": {
    title: "Terms of Service | Digital Therapy",
    description: "Digital Therapy terms of service.",
    priority: 0.2,
  },
  "/privacy": {
    title: "Privacy Policy | Digital Therapy",
    description: "How Digital Therapy collects, uses, and protects your information.",
    priority: 0.2,
  },
  "/accessibility": {
    title: "Accessibility | Digital Therapy",
    description: "Digital Therapy's commitment to an accessible, inclusive web experience.",
    priority: 0.2,
  },
  "/404": {
    title: "Page Not Found | Digital Therapy",
    description: "The page you are looking for could not be found.",
    noindex: true,
  },
};

const DEFAULT_META: RouteMeta = ROUTE_META["/404"];

/**
 * Dynamic, non-prerendered routes whose paths carry an id/token, so they have no
 * exact ROUTE_META entry. Matched by prefix AFTER exact lookup so they don't
 * fall back to the "Page Not Found" default. All noindex (private/token-gated).
 */
const PREFIX_META: { prefix: string; meta: RouteMeta }[] = [
  {
    prefix: "/nda/sign",
    meta: {
      title: "Sign your Mutual NDA · Digital Therapy",
      description: "Review and electronically sign your mutual non-disclosure agreement with Digital Therapy.",
      noindex: true,
    },
  },
  {
    prefix: "/vendorlists",
    meta: { title: "Vendor Lists · Digital Therapy", description: "Digital Therapy admin console.", noindex: true },
  },
  {
    prefix: "/admin",
    meta: { title: "Admin · Digital Therapy", description: "Digital Therapy admin console.", noindex: true },
  },
];

/** Normalize a pathname (strip trailing slash, default to "/"). */
export function normalizePath(pathname: string): string {
  if (!pathname) return "/";
  const stripped = pathname.replace(/\/+$/, "");
  return stripped === "" ? "/" : stripped;
}

export function getRouteMeta(pathname: string): RouteMeta {
  const p = normalizePath(pathname);
  if (ROUTE_META[p]) return ROUTE_META[p];
  for (const { prefix, meta } of PREFIX_META) {
    if (p === prefix || p.startsWith(prefix + "/")) return meta;
  }
  return DEFAULT_META;
}

/** Absolute canonical URL for a path. */
export function canonicalFor(pathname: string): string {
  const p = normalizePath(pathname);
  return p === "/" ? `${SITE.url}/` : `${SITE.url}${p}`;
}

/** Absolute URL for an asset path (e.g. og image). */
export function absoluteUrl(assetPath: string): string {
  if (/^https?:\/\//.test(assetPath)) return assetPath;
  return `${SITE.url}${assetPath.startsWith("/") ? "" : "/"}${assetPath}`;
}

/** Routes that belong in sitemap.xml (everything indexable). */
export function sitemapRoutes(): { path: string; priority: number }[] {
  return Object.entries(ROUTE_META)
    .filter(([, m]) => !m.noindex)
    .map(([path, m]) => ({ path, priority: m.priority ?? 0.7 }));
}
